# Generated by Django 2.2.6 on 2019-10-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjobresponses',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
