# Generated by Django 2.2.6 on 2019-10-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='allert_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cronjob',
            name='exec_offset',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cronjob',
            name='save_response',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
