# Generated by Django 2.2.6 on 2019-10-10 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0002_cronjobresponses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobresponses',
            name='cronjob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.CronJob'),
        ),
    ]
