# Generated by Django 2.2.6 on 2019-10-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0002_auto_20191007_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='allert_type',
            field=models.IntegerField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='exec_offset',
            field=models.IntegerField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='save_response',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
