# Generated by Django 2.2.6 on 2019-10-09 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0003_cronjob_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
