# Generated by Django 2.2.6 on 2019-10-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0004_auto_20191009_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjob',
            name='exec_day',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='exec_hour',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='exec_minute',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='exec_month',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='exec_weekday',
        ),
        migrations.AddField(
            model_name='cronjob',
            name='execute_interval',
            field=models.CharField(default='* * * * *', max_length=255),
        ),
    ]
