# Generated by Django 2.2.6 on 2019-10-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0006_cronjobresponses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobresponses',
            name='cronjob',
            field=models.IntegerField(),
        ),
    ]
