# Generated by Django 2.2.6 on 2019-10-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0007_auto_20191010_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjobresponses',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
