# Generated by Django 2.2.6 on 2019-10-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0008_cronjobresponses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobresponses',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
