# Generated by Django 2.2.6 on 2019-10-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0011_auto_20191010_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobresponses',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
