# Generated by Django 2.2.6 on 2019-10-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0013_auto_20191010_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobresponses',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
